spring.application.name=url-shortener
server.port=8080

spring.datasource.url=jdbc:h2:mem:urlshortener_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.mvc.view.prefix=/WEB-INF/jsps/
spring.mvc.view.suffix=.jsp

app.qr.path=src/main/webapp/qr/
